name: technical-analysis
services:
  frontend:
    build: ./frontend
    environment:
      - ENV=debug
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ROOT_USERNAME
      - ROOT_PASSWORD
      - BACKEND_URL=http://scraper:8000
    ports:
      - "3000:3000"
    depends_on:
      - scraper
      - mongodb

  scraper:
    build: ./backend/scraper
    environment:
      - ENV=debug
      - PLAYWRIGHT_TIMEOUT=10000
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    expose:
      - "27017"
    ports:
      - "27017:27017"
    
volumes:
  mongo-data: {}